CC      = x86_64-w64-mingw32-gcc
LD      = x86_64-w64-mingw32-ld
AR      = x86_64-w64-mingw32-ar
CFLAGS  = -I../api -I../efiutil/include -ffreestanding -fno-stack-protector \
 -fshort-wchar
LDFLAGS = -shared --image-base 0x400000 -e efi_main -subsystem 10
LIBS = -L../efiutil -lefiutil

ifeq ($(shell uname -m),x86_64)
	CFLAGS  += -mno-red-zone
	LDFLAGS += -T ../tools/x86_64-efi.ld -m i386pep
else
	LDFLAGS += -T ../tools/ia-32-efi.ld -m i386pe
endif

%.o: %.c
	$(CC) $(CFLAGS) -c $^ -o $@
